ruby/config/routes.rb
PaymentServer::Application.routes.draw do

  get "friends/show"

  get "friends/create"

  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'transaction#balance'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/users/valid', to: 'users#valid', via: :post

  match '/transfer', to: 'transaction#create', via: :post
  match '/transfer', to: 'transaction#new', via: :get
  match '/transfer/new', to: 'transaction#form', via: :get
  match '/transactions(/:id)', to: 'transaction#transactions', :as => :transactions
  match '/balance', to: 'transaction#balance', via: :get

  match '/token', to: 'transaction#token', via: :get
  match '/token', to: 'transaction#gen_token', via: :post
  match '/token', to: 'transaction#put_token', via: :put

  match '/friends', to: 'friends#show', via: :get
  match '/friends', to: 'friends#create', via: :post

  get '/sessions', to: redirect('/')
  get '/signout', to: redirect('/signin')

end

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>
<body class="ui-mobile-viewport">

<div data-role="page" data-theme="dva">


  <div class="header ui-header ui-bar-dva" data-backbtn="false" data-role="header" data-theme="dva" role="banner">
    <div class="logo"></div>
    <% if signed_in? %>
        <%= link_to signout_path, method: "delete",
                    "class" => "logoff ui-btn-right ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all",
                    'data-corners' => "true", 'data-shadow' => "true", 'data-iconshadow' => "true",
                    'data-wrapperels' => "span", 'data-theme' => "c" do %>
        <span class="ui-btn-inner ui-btn-corner-all">
          <span class="ui-btn-text">Log Out</span>
        </span>
        <% end %>

        <div class="navbar ui-navbar ui-navbar-noicons" role="navigation">
          <ul class="ui-grid-b">
            <li class="ui-block-a">
              <%= link_to balance_path, 'class' => active_page(yield(:title), 'My Accounts'), 'data-corners' => "false",
                          'data-shadow' => "false", 'data-iconshadow' => "true", 'data-wrapperels' => "span", 'data-theme' => "a",
                          'data-inline' => "true" do %>
                  <span class="ui-btn-inner"><span class="ui-btn-text">Accounts</span></span>
              <% end %>
            </li>
            <li class="ui-block-b">
              <%= link_to transfer_path, 'class' => active_page(yield(:title), 'Transfer'), 'data-corners' => "false",
                          'data-shadow' => "false", 'data-iconshadow' => "true", 'data-wrapperels' => "span", 'data-theme' => "a",
                          'data-inline' => "true" do %>
                  <span class="ui-btn-inner"><span class="ui-btn-text">Transfer</span></span>
              <% end %>
            </li>
            <li class="ui-block-c">
              <%= link_to current_user, 'class' => active_page(yield(:title), 'Profile'), 'data-corners' => "false",
                          'data-shadow' => "false", 'data-iconshadow' => "true", 'data-wrapperels' => "span", 'data-theme' => "a",
                          'data-inline' => "true" do %>
                  <span class="ui-btn-inner"><span class="ui-btn-text">Profile</span></span>
              <% end %>
            </li>
          </ul>
        </div>
    <% end %>
  </div>
  <!-- /header -->

  <div class="content" data-role="content">
    <p data-theme="d" id="notice"><%= notice %></p>
    <%= yield %>
  </div>
  <!-- /content -->

  <div class="footer ui-footer ui-bar-dva" data-backbtn="false" data-role="footer" data-theme="dva" role="contentinfo">
    <div class="footer-navbar ui-footer-navbar">
      <ul>
        <li class="navbar-item" style="border: none;color: #e67e22;">
          <%= link_to 'Damn Vulnerabile App (DVA) Payments', root_path, 'class' => 'ui-btn-active ui-link', 'style' => 'color: #9c5750;' %>
        </li>
      </ul>
    </div>
  </div>
  <!-- /footer -->
</div>

</body>
</html>